# Generated by Django 2.2.3 on 2019-07-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(upload_to='event_image/')),
                ('event_title', models.CharField(max_length=200)),
                ('event_desc', models.TextField(max_length=5000)),
                ('event_from', models.DateField(blank=True, default=True)),
                ('event_time_from', models.TimeField(blank=True, default=True)),
                ('event_time_to', models.TimeField(blank=True, default=True)),
                ('event_create', models.DateTimeField(auto_now_add=True)),
                ('event_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='banner_image/')),
                ('banner_desc', models.CharField(max_length=256)),
                ('banner_alt_txt', models.CharField(max_length=100)),
                ('banner_img_txt1', models.CharField(max_length=50)),
                ('banner_img_txt2', models.CharField(max_length=20)),
                ('banner_btn_name', models.CharField(max_length=20)),
                ('banner_created_date', models.DateTimeField(auto_now_add=True)),
                ('banner_updated_date', models.DateTimeField(auto_now=True)),
                ('banner_status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default=True, max_length=10)),
                ('banner_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexHeadOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_head', models.CharField(max_length=55)),
                ('index_head_str', models.CharField(max_length=55)),
                ('index_desc', models.CharField(max_length=200)),
                ('index_created', models.DateTimeField(auto_now_add=True)),
                ('index_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexHeadTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_head_two', models.CharField(max_length=55)),
                ('index_head_two_str', models.CharField(max_length=55)),
                ('index_desc_two', models.CharField(max_length=200)),
                ('index_created_two', models.DateTimeField(auto_now_add=True)),
                ('index_updated_two', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoreDiscoverMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_img', models.ImageField(upload_to='discover_menu_imgae/')),
                ('menu_url', models.CharField(max_length=20)),
                ('menu_btn', models.CharField(max_length=20)),
                ('menu_created_date', models.DateTimeField(auto_now_add=True)),
                ('menu_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopularCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_course_img', models.ImageField(upload_to='popular_course_images/')),
                ('pupular_course_head', models.CharField(max_length=100)),
                ('pupular_course_subhead', models.CharField(max_length=100)),
                ('popular_course_desc', models.CharField(max_length=300)),
                ('popular_course_created', models.DateTimeField(auto_now_add=True)),
                ('popular_course_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
