# Generated by Django 2.2.3 on 2019-07-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(upload_to='event_image/')),
                ('event_title', models.CharField(max_length=200)),
                ('event_desc', models.TextField(max_length=5000)),
                ('event_from', models.DateField(blank=True)),
                ('event_time_from', models.TimeField(blank=True)),
                ('event_time_to', models.TimeField(blank=True)),
                ('event_create', models.DateTimeField(auto_now_add=True)),
                ('event_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
