# Generated by Django 2.2.3 on 2019-07-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0002_auto_20190711_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='slug',
            field=models.SlugField(default='', max_length=264),
        ),
    ]
