# Generated by Django 2.2.3 on 2019-07-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0005_auto_20190712_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_desc', models.TextField(max_length=5000)),
                ('videofile', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
