# Generated by Django 2.2.3 on 2019-07-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0007_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcourses',
            name='slug',
            field=models.SlugField(default='', max_length=264),
        ),
        migrations.AlterField(
            model_name='popularcourses',
            name='popular_course_desc',
            field=models.TextField(max_length=50000),
        ),
    ]
