# Generated by Django 2.2.3 on 2019-07-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0008_auto_20190712_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=13)),
                ('email_id', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=30)),
                ('course', models.CharField(choices=[('Aerospace Engineering', 'Aerospace Engineering'), ('Agriculture Courses', 'Agriculture Courses'), ('Fashion Technology', 'Fashion Technology'), ('Marine Engineering', 'Marine Engineering'), ('Building, Construction Management', 'Building, Construction Management'), ('Web Development', 'Web Development'), ('Accountant course', 'Accountant course'), ('Dot Net Development', 'Dot Net Development'), ('Java Development', 'Java Development'), ('Chemical Engineering', 'Chemical Engineering')], default='', max_length=100)),
            ],
        ),
    ]
