# Generated by Django 2.2.3 on 2019-07-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0010_auto_20190715_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_title', models.CharField(max_length=30)),
                ('admission_desc', models.TextField()),
                ('admission_help', models.CharField(max_length=30)),
                ('admission_help_no', models.CharField(max_length=15)),
            ],
        ),
    ]
