# Generated by Django 2.2.3 on 2019-07-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0012_award_awardlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardlist',
            name='slug',
            field=models.SlugField(default='', max_length=264),
        ),
    ]
