# Generated by Django 2.2.3 on 2019-07-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0015_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.CharField(max_length=200)),
                ('contact_address', models.CharField(max_length=200)),
                ('contact_phone', models.IntegerField()),
                ('contact_mobile', models.IntegerField(max_length=12)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_website', models.CharField(blank=True, max_length=50)),
                ('contact_facebook', models.CharField(blank=True, max_length=50)),
                ('contact_blog', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=25)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
