# Generated by Django 2.2.3 on 2019-07-16 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0016_contact_contactusform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('facility_img', models.ImageField(upload_to='facility_imgage/')),
                ('facility_desc', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility_created_date', models.DateTimeField(auto_now_add=True)),
                ('facility_updated_date', models.DateTimeField(auto_now=True)),
                ('facility_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'published')], default='draft', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_mobile',
            field=models.IntegerField(),
        ),
    ]
