# Generated by Django 2.2.3 on 2019-07-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0017_auto_20190716_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_img', models.ImageField(upload_to='department_image/')),
                ('department_icon_img', models.ImageField(upload_to='department_image/icon/')),
                ('department_duration', models.CharField(max_length=10)),
            ],
        ),
    ]
