# Generated by Django 2.2.3 on 2019-07-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0018_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeExpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('expo_desc', models.TextField()),
                ('expo_topic', models.CharField(max_length=100)),
                ('expo_location', models.CharField(max_length=55)),
                ('expo_date', models.DateField(blank=True)),
                ('expo_time', models.TimeField(blank=True)),
                ('expo_created', models.DateTimeField(auto_now_add=True)),
                ('expo_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
