# Generated by Django 2.2.3 on 2019-07-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0019_collegeexpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='event_location',
            field=models.CharField(default='', max_length=55),
        ),
    ]
