# Generated by Django 2.2.3 on 2019-07-17 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universityapp', '0021_eventregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_student', models.TextField()),
                ('student_id', models.CharField(max_length=20)),
                ('student_mobile_no', models.IntegerField()),
                ('date_of_birth', models.DateField(blank=True)),
                ('student_address', models.CharField(max_length=200)),
                ('student_img', models.ImageField(default='default.jpg', upload_to='student_profile_image/')),
                ('facebook_url', models.CharField(blank=True, max_length=100)),
                ('google_url', models.CharField(blank=True, max_length=100)),
                ('Twitter_url', models.CharField(blank=True, max_length=100)),
                ('terms_condition', models.CharField(max_length=300)),
                ('user_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
