# Generated by Django 2.2.3 on 2019-07-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0023_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_active', models.BooleanField(default=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityapp.PopularCourses')),
            ],
        ),
    ]
