# Generated by Django 2.2.3 on 2019-07-18 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universityapp', '0024_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_title', models.CharField(max_length=30)),
                ('exam_date_from', models.DateField()),
                ('exam_date_to', models.DateField()),
                ('exam_time_from', models.TimeField()),
                ('exam_time_to', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exam_active', models.BooleanField(default=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityapp.PopularCourses')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityapp.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityapp.Semester')),
            ],
        ),
    ]
