# Generated by Django 2.2.3 on 2019-07-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0025_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_sem', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='semester',
            name='user_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityapp.ExamSem'),
        ),
    ]
