# Generated by Django 2.2.3 on 2019-07-18 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universityapp', '0026_auto_20190718_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityapp.ExamSem')),
            ],
        ),
    ]
