# Generated by Django 2.2.3 on 2019-07-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0030_remove_semesterlist_user_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='exam_sem',
        ),
        migrations.RemoveField(
            model_name='semesterlist',
            name='exam_sem',
        ),
        migrations.AddField(
            model_name='semesterlist',
            name='user_semester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='universityapp.ExamSem'),
        ),
    ]
