# Generated by Django 2.2.3 on 2019-07-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0032_auto_20190718_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterlist',
            name='exam_sem',
        ),
    ]
