# Generated by Django 2.2.3 on 2019-07-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0034_semesterlist_exam_sem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemesterList',
        ),
    ]
