# Generated by Django 2.2.3 on 2019-07-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0036_auto_20190718_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacant',
            name='job_position',
            field=models.CharField(default='', max_length=20),
        ),
    ]
