# Generated by Django 2.2.3 on 2019-07-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0039_auto_20190719_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='event_img',
            field=models.ImageField(blank=True, upload_to='event_image/'),
        ),
    ]
