# Generated by Django 2.2.3 on 2019-07-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0041_auto_20190720_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='event_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
