# Generated by Django 2.2.3 on 2019-07-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0042_auto_20190720_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='event_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='event_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
