# Generated by Django 2.2.3 on 2019-07-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0043_auto_20190720_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_active',
        ),
    ]
