# Generated by Django 2.2.3 on 2019-07-23 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0045_auto_20190722_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='user',
        ),
        migrations.AlterField(
            model_name='exam',
            name='user_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityapp.ExamSem'),
        ),
    ]
