# Generated by Django 2.2.3 on 2019-07-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0046_auto_20190723_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date_to',
            field=models.DateField(blank=True),
        ),
    ]
