# Generated by Django 2.2.3 on 2019-07-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0047_auto_20190723_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_active',
        ),
        migrations.CreateModel(
            name='ExamSemBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_title', models.CharField(max_length=30)),
                ('exam_date_from', models.DateField()),
                ('exam_date_to', models.DateField(blank=True)),
                ('exam_time_from', models.TimeField()),
                ('exam_time_to', models.TimeField()),
                ('exam_duration', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityapp.PopularCourses')),
                ('exam_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityapp.ExamSem')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityapp.Subject')),
            ],
        ),
    ]
