# Generated by Django 2.2.3 on 2019-07-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0048_auto_20190723_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nocount', models.PositiveIntegerField(default='')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentcount', to='universityapp.Blog')),
            ],
        ),
    ]
