# Generated by Django 2.2.3 on 2019-07-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0049_sharecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharecount',
            old_name='comment',
            new_name='blog_title',
        ),
    ]
