# Generated by Django 2.2.3 on 2019-07-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0050_auto_20190726_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharecount',
            name='nocount',
            field=models.PositiveIntegerField(),
        ),
    ]
