# Generated by Django 2.2.3 on 2019-07-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0052_coursecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecomment',
            old_name='pcomment',
            new_name='popular_course',
        ),
    ]
