# Generated by Django 2.2.3 on 2019-07-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0053_auto_20190726_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='updated',
        ),
    ]
