# Generated by Django 2.2.3 on 2019-07-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0056_blogemailshare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogemailshare',
            old_name='blogshare',
            new_name='share',
        ),
    ]
