# Generated by Django 2.2.3 on 2019-07-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0057_auto_20190726_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogemailshare',
            old_name='share',
            new_name='comment',
        ),
    ]
