# Generated by Django 2.2.3 on 2019-07-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0058_auto_20190726_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogemailshare',
            name='email_from',
        ),
        migrations.RemoveField(
            model_name='blogemailshare',
            name='email_to',
        ),
        migrations.RemoveField(
            model_name='blogemailshare',
            name='message',
        ),
    ]
