# Generated by Django 2.2.3 on 2019-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityapp', '0059_auto_20190726_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogemailshare',
            name='email_from',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='blogemailshare',
            name='email_to',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='blogemailshare',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
